// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $admin_kv_inspector from "./routes/admin/kv-inspector.tsx";
import * as $admin_newsletter from "./routes/admin/newsletter.tsx";
import * as $api_add_test_subscriber from "./routes/api/add-test-subscriber.ts";
import * as $api_admin_kv_inspect from "./routes/api/admin/kv-inspect.ts";
import * as $api_blasts from "./routes/api/blasts.ts";
import * as $api_contact from "./routes/api/contact.ts";
import * as $api_generate_pdf from "./routes/api/generate-pdf.ts";
import * as $api_printAllChapters from "./routes/api/printAllChapters.ts";
import * as $api_subscribers from "./routes/api/subscribers.ts";
import * as $api_test_env from "./routes/api/test-env.ts";
import * as $api_upload from "./routes/api/upload.ts";
import * as $index from "./routes/index.tsx";
import * as $AddChapter from "./islands/AddChapter.tsx";
import * as $ChapterControls from "./islands/ChapterControls.tsx";
import * as $CollapsibleSection from "./islands/CollapsibleSection.tsx";
import * as $ContentFooter from "./islands/ContentFooter.tsx";
import * as $HomeContent from "./islands/HomeContent.tsx";
import * as $KvInspector from "./islands/KvInspector.tsx";
import * as $LoaderIsland from "./islands/LoaderIsland.tsx";
import * as $Newsletter from "./islands/Newsletter.tsx";
import * as $PdfPreview from "./islands/PdfPreview.tsx";
import * as $PdfPreviewChapterEditor from "./islands/PdfPreviewChapterEditor.tsx";
import * as $PdfPreviewSidebar from "./islands/PdfPreviewSidebar.tsx";
import * as $PortfolioHome from "./islands/PortfolioHome.tsx";
import * as $SearchBar from "./islands/SearchBar.tsx";
import * as $SearchResults from "./islands/SearchResults.tsx";
import * as $Sections from "./islands/Sections.tsx";
import * as $SubscribeForm from "./islands/SubscribeForm.tsx";
import * as $printAllChapters from "./islands/printAllChapters.tsx";
import * as $useSearch from "./islands/useSearch.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/admin/kv-inspector.tsx": $admin_kv_inspector,
    "./routes/admin/newsletter.tsx": $admin_newsletter,
    "./routes/api/add-test-subscriber.ts": $api_add_test_subscriber,
    "./routes/api/admin/kv-inspect.ts": $api_admin_kv_inspect,
    "./routes/api/blasts.ts": $api_blasts,
    "./routes/api/contact.ts": $api_contact,
    "./routes/api/generate-pdf.ts": $api_generate_pdf,
    "./routes/api/printAllChapters.ts": $api_printAllChapters,
    "./routes/api/subscribers.ts": $api_subscribers,
    "./routes/api/test-env.ts": $api_test_env,
    "./routes/api/upload.ts": $api_upload,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/AddChapter.tsx": $AddChapter,
    "./islands/ChapterControls.tsx": $ChapterControls,
    "./islands/CollapsibleSection.tsx": $CollapsibleSection,
    "./islands/ContentFooter.tsx": $ContentFooter,
    "./islands/HomeContent.tsx": $HomeContent,
    "./islands/KvInspector.tsx": $KvInspector,
    "./islands/LoaderIsland.tsx": $LoaderIsland,
    "./islands/Newsletter.tsx": $Newsletter,
    "./islands/PdfPreview.tsx": $PdfPreview,
    "./islands/PdfPreviewChapterEditor.tsx": $PdfPreviewChapterEditor,
    "./islands/PdfPreviewSidebar.tsx": $PdfPreviewSidebar,
    "./islands/PortfolioHome.tsx": $PortfolioHome,
    "./islands/SearchBar.tsx": $SearchBar,
    "./islands/SearchResults.tsx": $SearchResults,
    "./islands/Sections.tsx": $Sections,
    "./islands/SubscribeForm.tsx": $SubscribeForm,
    "./islands/printAllChapters.tsx": $printAllChapters,
    "./islands/useSearch.tsx": $useSearch,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
