// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $api_generate_pdf from "./routes/api/generate-pdf.ts";
import * as $api_imageProcessor from "./routes/api/imageProcessor.ts";
import * as $api_printAllChapters from "./routes/api/printAllChapters.ts";
import * as $api_upload from "./routes/api/upload.ts";
import * as $feedback from "./routes/feedback.tsx";
import * as $index from "./routes/index.tsx";
import * as $AddChapter from "./islands/AddChapter.tsx";
import * as $ChapterControls from "./islands/ChapterControls.tsx";
import * as $CollapsibleSection from "./islands/CollapsibleSection.tsx";
import * as $ContentFooter from "./islands/ContentFooter.tsx";
import * as $HomeContent from "./islands/HomeContent.tsx";
import * as $LoaderIsland from "./islands/LoaderIsland.tsx";
import * as $PdfPreview from "./islands/PdfPreview.tsx";
import * as $PdfPreviewChapterEditor from "./islands/PdfPreviewChapterEditor.tsx";
import * as $PdfPreviewSidebar from "./islands/PdfPreviewSidebar.tsx";
import * as $PortfolioHome from "./islands/PortfolioHome.tsx";
import * as $SearchBar from "./islands/SearchBar.tsx";
import * as $SearchResults from "./islands/SearchResults.tsx";
import * as $Sections from "./islands/Sections.tsx";
import * as $printAllChapters from "./islands/printAllChapters.tsx";
import * as $useSearch from "./islands/useSearch.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/api/generate-pdf.ts": $api_generate_pdf,
    "./routes/api/imageProcessor.ts": $api_imageProcessor,
    "./routes/api/printAllChapters.ts": $api_printAllChapters,
    "./routes/api/upload.ts": $api_upload,
    "./routes/feedback.tsx": $feedback,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/AddChapter.tsx": $AddChapter,
    "./islands/ChapterControls.tsx": $ChapterControls,
    "./islands/CollapsibleSection.tsx": $CollapsibleSection,
    "./islands/ContentFooter.tsx": $ContentFooter,
    "./islands/HomeContent.tsx": $HomeContent,
    "./islands/LoaderIsland.tsx": $LoaderIsland,
    "./islands/PdfPreview.tsx": $PdfPreview,
    "./islands/PdfPreviewChapterEditor.tsx": $PdfPreviewChapterEditor,
    "./islands/PdfPreviewSidebar.tsx": $PdfPreviewSidebar,
    "./islands/PortfolioHome.tsx": $PortfolioHome,
    "./islands/SearchBar.tsx": $SearchBar,
    "./islands/SearchResults.tsx": $SearchResults,
    "./islands/Sections.tsx": $Sections,
    "./islands/printAllChapters.tsx": $printAllChapters,
    "./islands/useSearch.tsx": $useSearch,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
